
20021519-101
@Author spy101

In [2]:
import pandas as pd
import numpy as np

In [26]:
list1 = [1,2,3,4,5,6,7,8,9,10]
list2 = [[1,2,3,4,5],[6,7,8,9,10]]

['73', '52', '80', '85', '64', '63', '60']

convert into ndarray  1D 2 D

In [9]:
array1 = np.array(list1)
array2 = np.array(list2)
type(array1)
print(array1)
print(array2)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

Operations

In [15]:
#aethemeticoperation on numpy array which is not possible in simple list 
array1-1
array2-2

array([[-1,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  8]])

Pandas

In [21]:
series1 = pd.Series(list1)
series2 = pd.Series(list2,index=['list1','list2'])
series1
series2

list1     [1, 2, 3, 4, 5]
list2    [6, 7, 8, 9, 10]
dtype: object

data frame

In [60]:
dataset = pd.read_csv('./Hartnagel.csv')
dataset

    sr  year   tfr  partic  degrees  fconvict  ftheft  mconvict  mtheft
0    1  1931  3200     234     12.4      77.1     NaN     778.7     NaN
1    2  1932  3084     234     12.9      92.9     NaN     745.7     NaN
2    3  1933  2864     235     13.9      98.3     NaN     768.3     NaN
3    4  1934  2803     237     13.6      88.1     NaN     733.6     NaN
4    5  1935  2755     238     13.2      79.4    20.4     765.7   247.1
5    6  1936  2696     240     13.2      91.0    22.1     816.5   254.9
6    7  1937  2646     241     12.2     100.4    22.4     821.8   272.4
7    8  1938  2701     242     12.6     108.9    21.8     956.8   285.8
8    9  1939  2654     244     12.3     123.6    21.1    1035.7   292.2
9   10  1940  2766     245     12.0     157.3    21.4     951.6   256.0
10  11  1941  2832     246     11.7     154.3    25.3     850.9   205.8
11  12  1942  2964     268     11.2     143.9    27.1     769.7   188.0
12  13  1943  3041     333     11.5     147.5    29.0     811.2   205.8
13  14  1944  3010     335     11.1      97.3    24.2     865.4   207.9
14  15  1945  3018     331     12.5      76.6    24.7     866.8   197.8
15  16  1946  3374     253     15.0      72.8    20.5     968.0   195.9
16  17  1947  3545     243     17.6      68.9    20.7     894.0   198.9
17  18  1948  3441     241     21.2      66.7    22.8     830.8   198.6
18  19  1949  3456     242     22.7      55.0    18.5     811.2   216.1
19  20  1950  3455     237     21.4      55.0    19.3     775.4   212.0
20  21  1951  3503     242     20.7      55.0    20.0     739.8   208.0
21  22  1952  3641     240     19.5      54.7    19.4     740.3   199.3
22  23  1953  3721     233     36.6      47.9    16.1     725.1   176.4
23  24  1954  3828     232     18.1      49.0    16.5     739.9   166.8
24  25  1955  3831     236     17.7      44.4    15.2     663.8   179.7
25  26  1956  3858     245     18.7      40.2    15.3     633.7   198.8
26  27  1957  3925     256     20.8      43.8    17.1     716.5   262.5
27  28  1958  3880     261     22.7      49.5    21.2     761.0   263.4
28  29  1959  3935     265     24.6      50.4    22.3     665.3   253.6
29  30  1960  3895     278     28.5      59.6    28.5     742.6   280.9
30  31  1961  3840     291     31.3      72.4    34.4     789.8   290.9
31  32  1962  3756     290     38.0      70.6    36.0     776.8   274.7
32  33  1963  3669     290     42.0      82.0    43.8     842.2   296.9
33  34  1964  3502     307     48.5      89.5    49.7     799.1   281.3
34  35  1965  3145     313     59.2     101.3    58.6     763.0   264.2
35  36  1966  2812     325     69.7     116.7    71.4     804.6   286.6
36  37  1967  2586     339     80.4     115.2    70.6     781.1   272.0
37  38  1968  2441     338     90.4     122.9    73.0     849.7   274.7

operations

In [59]:
# head 
dataset.head()
# at
dataset.at[2,'year']
#loc
dataset.loc[8,'sr']
#pop
dataset.pop('year')
dataset

9

search

In [65]:
dataset.loc[dataset['fconvict'] > 100]

    sr  year   tfr  partic  degrees  fconvict  ftheft  mconvict  mtheft
6    7  1937  2646     241     12.2     100.4    22.4     821.8   272.4
7    8  1938  2701     242     12.6     108.9    21.8     956.8   285.8
8    9  1939  2654     244     12.3     123.6    21.1    1035.7   292.2
9   10  1940  2766     245     12.0     157.3    21.4     951.6   256.0
10  11  1941  2832     246     11.7     154.3    25.3     850.9   205.8
11  12  1942  2964     268     11.2     143.9    27.1     769.7   188.0
12  13  1943  3041     333     11.5     147.5    29.0     811.2   205.8
34  35  1965  3145     313     59.2     101.3    58.6     763.0   264.2
35  36  1966  2812     325     69.7     116.7    71.4     804.6   286.6
36  37  1967  2586     339     80.4     115.2    70.6     781.1   272.0
37  38  1968  2441     338     90.4     122.9    73.0     849.7   274.7